src/components/listAthletes/index.tsx
src/contexts/athlete/athlete.tsx

Ajuste responsivo e redirect ao realizar chamada

feat: Ajustes lista chamada

---

src/app/globals.css
src/app/valencia/menu/page.tsx
src/components/formWrapper/index.tsx
src/components/listAthletes/index.tsx
src/components/listAvaliacao/index.tsx
src/components/listItem/index.tsx
src/components/timeInput/index.tsx
src/consts/const.ts
src/types/Assessment.ts
tailwind.config.ts

**Cria:**
- Novo componente de input de tempo
- Novo form wrapper
**Corrige:**
- Tipos de input de avaliações de valência
- Tema escuro em inputs e scroll bar
- Outras pequenas correções

Pisd 157 ajustes telas

---

src/components/formAtleta/index.tsx

remoção do direcionamento para a tela de perfil

fix: remoção redirect

---

src/components/formAtleta/index.tsx

fix: limpar foto avatar ao concluir o cadastro

fix: limpar avatar ao concluir o cadastro

---

src/components/listAvaliacao/index.tsx
src/components/timeInput/index.tsx
src/consts/const.ts

- Correção de placeholder no Chrome
- Adição de label superior no caso do IMC 
- Mudança de placeholder de IMC
- Remoção de Z-index obsoleto

Pequenas correções 

---

src/app/valencia/menu/page.tsx
src/components/modal/index.tsx
src/contexts/assessments/assessments.tsx
src/contexts/assessments/assessments.type.ts
src/contexts/assessments/index.ts
src/contexts/index.ts
src/providers/providers.tsx

- Novo context para Avaliações ('Assessments')
- Funções get e post para avaliações incompletas
- Modal para informar o usuário sobre as avaliações (Se tem ou para criar nova)
- Tratamento de erros
- Responsivo

feat: componente modal, modal avaliacoes completas e incompletas

---

src/app/valencia/menu/page.tsx
src/contexts/assessments/assessments.tsx

Comentada a função que chama o endpoint de avaliações incompletas.

fix: função comentada getIncompleteAssessments

---

src/components/reviewsChart/index.tsx

Componente gráfico criado , trazendo os dados da api

feat: componente grafico

---

src/components/posturaCard/index.tsx

Solução de UI para seleção de data no dropdown da visualização de posturas.

Feature header option

---

src/app/valencia/menu/page.tsx
src/contexts/assessments/assessments.tsx

- Ajuste path endpoint de verificação de avaliações incompletas
- Ajuste regra modal de criação
- Remoção modal de alerta para avaliações incompletas

fix: ajuste regra e endpoint modal de criacao de avaliacoes

---

src/app/valencia/menu/page.tsx
src/contexts/assessments/assessments.tsx

- Alterado endpoint chamado para criar avaliação
- Chamando a função de criar avaliação ao clicar no botão

fix: change endpoint, call function on click button

---

src/app/valencia/menu/page.tsx
src/components/listAvaliacao/index.tsx
src/consts/const.ts
src/contexts/api/api.tsx
src/contexts/athlete/athlete.tsx

- Refatoração do IMC (Agora com o comportamento de accordion)
- Corrige bug no Accordion com index do subitem
- Integra as avaliações com o Backend
- Adiciona bugs

Pisd 208 integracao avaliacao coletiva

---

src/components/listAvaliacao/index.tsx
src/consts/const.ts
src/types/Assessment.ts

Correção de uso indevido do slug na criação do body de requisição

Slug quick fix

---

src/components/formAtleta/index.tsx

fix: utilizando o contexto da api

---

src/app/atleta/perfil/[id]/page.tsx
src/components/frequency/index.tsx

usando o context api e passando id como parametro

fix: context api

---

src/app/atleta/perfil/[id]/page.tsx
src/contexts/athlete/athlete.tsx

fix: loop requisicoes perfil

---

src/components/frequency/index.tsx

remove 'get' de array de dependências do useEffect() no frequency que possuia comportamento errático ao consumir useApiProvider

Quick fix frequency

---

package-lock.json
package.json
src/app/atleta/editar/[id]/page.tsx
src/app/layout.tsx
src/components/formAtleta/formAtleta.module.css
src/components/formAtleta/index.tsx
src/contexts/athlete/athlete.tsx
src/schemas/athleteSchema.ts

- Ajustes css da tela de editar atleta e mudança no layout
- Ajuste da função de editar atleta (Salvar foto)
- Adicionado padding no layout para ter espaçamento do header e footer
- Lib switch button para ativo e inativo no cadastro/edição do atleta

Pisd 274/ajustes tela editar atleta

---

public/svg/injuries/Back.tsx
public/svg/injuries/Front.tsx
src/app/atleta/perfil/[id]/page.tsx
src/components/injuries/index.tsx

- Conserta espaçamento horizontal de botões dos componentes do perfil de atleta
- Conserta o comportamento do CSS do componente de lesões:
Desktop view:
Mobile view:

Quick fix lesoes

---

package.json
src/app/atleta/perfil/[id]/page.tsx
src/contexts/athlete/athlete.tsx
src/contexts/athlete/athlete.type.ts

Correções na lista de lesões:
- Ordenação reversa por data
- Correção na formatação da data
- Exibindo regiao da lesao

Squashed commits

---

src/components/formWrapper/index.tsx
src/components/listAthletes/index.tsx
src/contexts/athlete/athlete.tsx

Ajustado CSS da lista de chamada.
Atualizado listagem de atletas após a chamada ser realizada.

Fix lista de chamada

---

src/api/api.ts

Aumentado o timeout (nas configurações do axios específico do Busca Atleta) para 20seg.

increase request timeout
